Database:
  Tipo: SQLITE #Tipos: MYSQL, SQLITE, MYSQL_FAST
  IP: localhost:3306
  DB: test
  User: admin
  Pass: ''
  Debug: true

# Comandos e aliases do plugin
Comando:
  Correio:
    Comando: 'correio'
    Aliases: [ correios, encomendas, courier ]

# Tipo de formatos de quantia disponíveis: LETRA (K,M,B,T...) e NUMERO (100,00)
Formatacao: 'LETRA'

# Opcoes de configuração do NPC
NPC:
  ID: 923292
  Skin: 'ySpeed_'
  Holograma:
    Altura: 3.1
    Holograma:
      - '&6Correio'
      - '&7Clique para gerenciar suas encomendas.'

# Opções gerais do plugin
Opcoes:
  NPC-Name-Hide: false
  # Mundos onde não pode coletar encomendas/recompensas
  World blacklist:
    - 'none'
  # Enviar aviso de recompensas/encomendas no correio ao logar
  Logar mensagem: true
  # Limite de encomendas no correio
  Limite encomenda: 40
  # Ativar o sistema de encomendas
  Encomendas ativar: true
  # Delay para carregar os dados depois do login
  # Necessário para usar em servidor de mina separado
  # Recomendado: 20 ticks
  Login delay: 20
  # Ativar o botão Q para deletar as recompensas
  UsarQ: true

# Mensagens gerais do plugin
Mensagens:
  Permissao: '&cVocê não possui permissão para isto.'
  Setado npc: '&aNPC do correio setado com sucesso.'
  Removido npc: '&aNPC do correio removido com sucesso'
  Nao setado npc: '&cO NPC não está setado.'
  Cancelou: '&cVocê cancelou a operação'
  Nao encontrado: '&cEste jogador não foi encontrado.'
  Enviou: '&aVocê enviou &f{quantia}x &aitens para o jogador &f{player}&a.'
  Recebeu: '&aVocê recebeu &f{quantia}x &aitens do jogador &f{player}&a. Acesse &f/correio&a para recolher.'
  Enviou todos: '&aVocê enviou &f{quantia}x &aitens para todos os jogadores online.'
  Enviou grupo: '&aVocê enviou &f{quantia}x &aitens para todos os jogadores do grupo &f{grupo}&a.'
  Recebeu todos: '&aTodos os jogadores receberam &f{quantia}x &aitens no /correio.'
  Recebeu grupo: '&aTodos os jogadores do grupo &f{grupo}&a receberam &f{quantia}x &aitens no /correio.'
  Fechar: '&cNão é possível fechar este inventário sem recolher os itens.'
  Inserir: '&cVocê deve inserir itens no menu.'
  Si mesmo: '&cVocê não pode realizar esta operação em si mesmo.'
  Deletado: '&cItem deletado com sucesso.'
  Deletado recompensa: '&cRecompensa deletada com sucesso.'
  InvCheio: '&cSeu inventário está cheio.'
  Recolheu encomenda: '&aVocê recolheu &f{quantia}x &aencomendas com sucesso.'
  Recolheu recompensa: '&aVocê recolheu &f{quantia}x &arecompensas da categoria &f{categoria}&a com sucesso.'
  Mundo: '&cVocê não pode coletar neste mundo.'
  Recompensas: '&aLista de recompensas disponíveis: &f{lista}&a.'
  Grupos: '&aLista de grupos disponíveis: &f{lista}&a.'
  Categorias: '&aLista de categorias disponíveis: &f{lista}&a.'
  Nao encontrado grupo: '&cEste grupo não existe. Disponíveis: &7{grupos}&c.'
  Nao encontrado categoria: '&cEsta categoria não existe. Disponíveis: &7{categorias}&c.'
  Nao encontrado recompensa: '&cEsta grupo recompensa existe. Disponíveis: &7{recompensas}&c.'
  Give player: '&aVocê deu &f{quantia}x &f{recompensa}&a na categoria &f{categoria}&a para o jogador &f{player}&a.'
  Give todos: '&aVocê deu &f{quantia}x &f{recompensa}&a na categoria &f{categoria}&a para todos os jogadores online.'
  Give grupo: '&aVocê deu &f{quantia}x &f{recompensa}&a na categoria &f{categoria}&a para todos os jogadores do grupo &f{grupo}&a.'
  Recebeu player: '&aVocê recebeu &f{quantia}x &f{recompensa}&a na categoria &f{categoria}&a.'
  Recebeu player actionbar: '&a+ &f{quantia}x &f{recompensa}&a na categoria &f{categoria}&a.'
  Numero: '&cO argumento não é um número.'
  Limite encomenda: '&cEste jogador atingiu o limite de 40 encomendas.'
  Nenhuma: '&cNenhuma categoria foi configurada.'
  Encomenda desativado: '&cO sistema de encomendas foi desativado.'
  Digite:
    - ''
    - '&aDigite o nome do jogador que deseja enviar itens.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Possui encomenda:
    - ''
    - '&aVocê possui &f{encomendas}&a encomenda(s) no seu /correio.'
    - ''
  Possui recompensa:
    - ''
    - '&aVocê possui &f{recompensas}&a recompensa(s) no seu /correio.'
    - ''
  Possui recompensa encomenda:
    - ''
    - '&aVocê possui &f{encomendas} encomenda(s)&a e &f{recompensas} recompensa(s)&a no seu /correio.'
    - ''
  Help:
    - '&aComandos disponíveis:'
    - ''
    - '&f > &a/correio &8- &7Abre o menu principal'
    - '&f > &a/correio ajuda &8- &7Envia esta mensagem'
    - '&f > &a/correio enviar [player] &8- &7Envia itens à um jogador.'
    - ''
  Help admin:
    - '&aComandos disponíveis:'
    - ''
    - '&f > &a/correio &8- &7Abre o menu principal'
    - '&f > &a/correio ajuda &8- &7Envia esta mensagem'
    - '&f > &a/correio enviar [player] &8- &7Envia itens à um jogador.'
    - '&f > &a/correio enviartodos &8- &7Envia itens à todos os jogadores online.'
    - '&f > &a/correio enviargrupo [grupo] &8- &7Envia itens à todos os jogadores online de um grupo.'
    - '&f > &a/correio give [player] [categoria] [recompensa] [quantia] &8- &7Dá x recompensa(s) configurada à um jogador.'
    - '&f > &a/correio giveall [categoria] [recompensa] [quantia] &8- &7Dá x recompensa(s) configurada à todos os jogadores online.'
    - '&f > &a/correio givegrupo [grupo] [categoria] [recompensa] [quantia] &8- &7Dá x recompensa(s) configurada à todos os jogadores online de um grupo.'
    - '&f > &a/correio recompensas &8- &7Vê a lista de recompensas configuradas.'
    - '&f > &a/correio grupos &8- &7Vê a lista de grupos configurados.'
    - '&f > &a/correio categorias &8- &7Vê a lista de categorias configuradas.'
    - '&f > &a/correio setnpc &8- &7Seta o NPC do correio.'
    - '&f > &a/correio delnpc &8- &7Deleta o NPC do correio.'
    - ''

# Lores de sobreposição
Lores:
  Principal:
    Ativar: true
    Lore:
      - ''
      - '&aBotão esquerdo para coletar'
      - '&aBotão Q para deletar'
  Recompensa:
    Ativar: true
    Lore:
      - ''
      - '&fQuantia: &b{quantia}&f.'
      - ''
      - '&aBotão ESQUERDO para coletar'
      - '&aBotão Q para deletar'
      - '&aBotão SHIFT+ESQUERDO para coletar todos'

# Setas dos menus
Setas:
  Voltar:
    CustomSkull: false
    URL: ''
    ID: ARROW
    Data: 0
    Glow: true
    Name: '&cVoltar'
    Lore:
      - '&7Clique para voltar ao menu anterior.'
  Anterior:
    CustomSkull: false
    URL: ''
    ID: ARROW
    Data: 0
    Glow: true
    Name: '&cAnterior'
    Lore:
      - '&7Clique para voltar à página anterior.'
  Proximo:
    CustomSkull: false
    URL: ''
    ID: ARROW
    Data: 0
    Glow: true
    Name: '&aPróxima'
    Lore:
      - '&7Clique para ir à próxima página.'

# Formatos de quantia
Formats:
  - ''
  - ''
  - 'K'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'O'
  - 'N'
  - 'D'